[package]

name = "chip8"
version = "0.0.1"
authors = ["Jake Kerr <kodafox@gmail.com>"]

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"

[dependencies.pistoncore-event]
git = "https://github.com/pistondevelopers/event"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"

[dependencies.piston2d-opengl_graphics]
git = "https://github.com/pistondevelopers/opengl_graphics"

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"

[dependencies.pistoncore-input]
git = "https://github.com/pistondevelopers/input"

[dependencies.pistoncore-window]
git = "https://github.com/pistondevelopers/window"

[dependencies.quack]
git = "https://github.com/pistondevelopers/quack"

